services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: ai_fashion_db
    environment:
      POSTGRES_DB: ai_fashion_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai_shop_network

  redis:
    image: redis:7-alpine
    container_name: ai_fashion_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_shop_network

volumes:
  postgres_data:
  redis_data:

networks:
  ai_shop_network:
    driver: bridge